PESTS = {
    "fall_armyworm": {
        "name": "Fall Armyworm",
        "protein": "Chitin synthase CHS-2 isoform X2",
        "sequence": (
            "MSDNDRKSHYERDDAEEPLYIANNNNSIYSNGTLHYCSIYSQRTVQETKGWDVFREFPPKQDSGSMETQK"
            "CLEFTVRLLKVTAYLVVFIAVLGSGVVAKGSTLFMTSQLKKDRRIAYCNRNLGRDKQFIVSLPDEERVAW"
            "MWAILAAFAIPEIGTLIRSVRICFFKTSRRPTSTQFAVIFIAETLHTIGMGLLFFMILPELDVVKGAMIT"
            "NCLCIIPAVLGLLSRNSRDSKRFMKVIVDMAAIVAQVTGFIVWPLLENKPVLWLIPVASLCISLGWWENY"
            "VTRQSPIGIIKSLGRLKDELTFTRYYTYRFISVWKILVFLMCILFMIWVDGDEPAMFFQLFNAGFGPHSI"
            "VVEEVQIQLGGTVIPDLANVTLTGDSVEVAAAYKSAFYVLLIQVFAAYICYIFGKFACKILIQGFSYAFP"
            "INLVIPLVVNLLIAACGIRNGDNCYFHGTVPDYLYFESPPVFTLSDFISRQMAWIWLLWLLSQTWITIHI"
            "WTPKAERLASTEKLFVMPMYNGLLIDQSMALNRKRNDQRDVKTEDLAEIEKEKGDEYYETISVHTDNTGS"
            "SPKAIKSSDQITRIYACATMWHETKDEMMEFLKSILRLDEDQCARRVAQKYLRVVDPDYYEFETHIFLDD"
            "AFEISDHSDDDAQVNRFVKLLVDTIDEAASEVHQTNIRIRPPKKYPAPYGGRLTWVLPGKTKMICHLKDK"
            "AKIRHRKRWSQVMYMYYLLGHRLMELPISVDRKEVMAENTYLLTLDGDIDFQPHAVRLLIDLMKKNKNLG"
            "AACGRIHPVGSGPMVWYQMFEYAIGHWLQKATEHMIGCVLCSPGCFSLFRGKALMDDNVMKKYTLRSDEA"
            "RHYVQYDQGEDRWLCTLLLQRGYRVEYSAASDAYTHCPEGFNEFYNQRRRWVPSTIANIMDLLADCKHTI"
            "KINDNISSPYIAYQMMLMGGTILGPGTIFLMLVGAFVAAFRIDNWTSFEYNLYPILIFMFVCFTMKSEIQ"
            "LLVAQILSTAYAMIMMAVIVGTALQLGEDGIGSPSAIFLISLSSSFFIAACLHPQEFWCIVPGIIYLLSI"
            "PSMYLLLILYSIINLNVVSWGTREVAVKKTKKEIEAEKKEAELAKKSAKQKSLLGFLQGVNSNEEEGSIE"
            "FSFAGLFKCLLCTHPKGNEEKVQLLHIASTLEKLEKKLETVERAVDPHGMSRGRKLSVGPRGSNAGDHGL"
            "DALAEGPEEDDDSDSETDTLSTTPREKRDDLINPYWIEDPELKKGEVDFLSPAELSFWKDLIDKYLYPID"
            "ENKEEKARIAGDLLELRNKSVFAFVMFNALFILIVFLLQLNKDQLHVIWPLGIKTNITYIEETGEVLISK"
            "EYLQLEPIGLVFVFFFALILVIQFSAMLFHRFGTLSHILASTELNWFCSKKSDDLSQDALLDKNAIAIVK"
            "DLQKLNGLDDDYDNDSGSGPHNVGRRKTIHNLEKARQKKRNIGTLDVAFKKRFFNMNANDGPGTPVLNRK"
            "MTLRRETLKALETRRNSVMAERRKSQMQTLGANNEYGVTGMLNNNLNVGPRHRTSNANISVKDVFGEPNG"
            "GQVNRGYETTLGDEDDTNSMRLQPRQNQVSFQGRF"
        ),
    },

    "aphid": {
        "name": "Aphid",
        "protein": "Acetylcholinesterase",
        "sequence": (
            "MDQWLLWFGYLVASTYGLSLRHARHQSVGTPTAEEILEPQILIEDTDHVFRQRASDMFAQEPEYTEKRNL"
            "NHRRRSEFSGNQDTNFESSGATYSAYTSDDPLIIHTNKGKIRGITQEATTGKLVDAWLGIPYAKKPIGDL"
            "RFRHPRPIDRWDTTSPETILNCTTPPNTCVQIFDTLFGDFPGATMWNPNSPVSEDCLYINVVVPRPRPQN"
            "AAVMVWIFGGGFYSGSATLDIYDPKILVSEENVILVSMQYRVASLGFLYFDTEDVPGNAGLFDQLMALQW"
            "VHENIKLFGGNPNNVTLFGESAGAVSVSLHLLSPLSRNLFNQAIMESGSSTVPWAILSREESFSRGLKLA"
            "KAMGCPDDRNEIHKTVECLRKVNSSAMVEKEWDHVAMCFFPFVPVVDGAFLDDHPQKSLSTNNFKKTNIL"
            "MGSNSEEGYYFIFYYLTELFKKEENVVVSRENFIKAIGQLNPNADAAVKSAIEFEYTDWFNPNDPEKNRN"
            "ALDKMVGDYQFTCNVNEFAHKYALTGNNVYMYYFKHRSLNNPWPKWTGVMHGDEISYVFGDPLNPNKRYE"
            "IEEIELSKKMMRYWTNFAKTGNPSKTLEGSWVTPKWPVRTAYGKEFLTLDTNNTSIGVGPRLEQCAFWKN"
            "YVPDLTVISKSMKSDKNCTTISGGTKTNMIKLSVWTIVMTTAVLML"
        ),
    },

    "colorado_potato_beetle": {
        "name": "Colorado Potato Beetle",
        "protein": "Sodium channel protein 60E",
        "sequence": (
            "MSSPTDESPVPTSTGPPALASIDPLAPPPKNEPFTDPLQQQTDTNQDVEVKPGDGALSPLPKRPISYPYG"
            "PESGIEPPPRVELIGFNPLKRNSDPLKVAAAKNKTQVKPFTRESLEKLQKKTVQLVREYGFQPRRKLSVE"
            "DGSRLPAKFEPFPTKLYGRPLEEIDNFIYDETFCVVSKRFRKNYIHRFTATNSFFYFSPFNPFRKACIYL"
            "CTNQYFDYLVMATILLNCVFLAMAETIEEAEYIFLAIYTLEMIIKTIAKGFILNKYTYLRNPWNWLDFVV"
            "ITSGYATIGMEVGNLAGLRTFRVLRALKTISILPGLKTIINALLHSFKQLAEVMTLTIFCLMVFALFALQ"
            "VYKGELRNKCVLKMDDHNASYETWFNYTQDPSNWLRRNSTGEPYLCGNVTGSRHCPPTHTCLCTGGNPNH"
            "GYTSFDNFLWSMLTTFQLITLDYWENVYNMVLSACGPISVSFFTVVVFFGSFYLINLMLAVVALSYEEEA"
            "EITQEERKKELVDHREDSTFSFDPTNLNVKKLSKQKIKKIDARKGVLLSSYTRKKTRRRKRNRSSTNAAK"
            "TNATENNGNKQETKDSSSNKSSPKKNPKRSVTPSRSPSPRHSQHSQQSQESPRPQVLPLVVPLPLPPPKH"
            "VHMSDSKRTDTLHPHNTLGPNPNRLGLQSRQASSNSGEGNNRESSLDDSGVVDDHEPEGDATSEEVGTHL"
            "TPSSRRIEVTPVTVAVGPKEIKVIKCNGVGSCKKKEMYTLQPDYLSHIVVINQQIPDRNCSGCEQCCMDY"
            "EGWIQFQQGLYQIVRDPLFELAITVCIVLNTMFLAMEHHGMSESVLRALDIGNKVFTSIFTFECCLKIMA"
            "LSKDFFYCGWNIFDLIIVSASLLDLIFELVDGLSVLRGLRLLRVLKLAQSWITMKVLLSIIISTIGALGN"
            "LTFVLVIVIYIFAVIGMQLFAKDYTEEKFFPDPIPRWNFTDFFHSFMMIFRILCGEWIEPLWDCMRAEKT"
            "EGPGTCLAVFLPTLVMGNFMVLNLFLALLLNSFNSEELKTRKEVYDTFFELQEVGDESKLAQSFQRIRDL"
            "VRKRRMAEQDQNENNSRLEQIVREVMQRHAEEEAFRNAEKSARSVQQIGFPRDKRSYQEAMNRPISIISY"
            "EPPEYQEKPPESEKSNRSSKLYSSLLTTSEESGTPTTEKKKNDTKRLCNMSSELGTTNSSKDETTNLIAK"
            "SNNRTSTESENEDANDGRKKICDKNNEARGGDMPWQTLVSYVDELTVGGRRNSKGQYIDGMGTFPGFGKK"
            "KPPRAAPDCFPSNFYERCTCLNRCTETKIGQKWINLRKLILSVVDTSGFEWFILVLIFASSVTLCFEDIH"
            "LDENPDLKSVLYWTNLAFSIIFIIEMFLKWIALGFYEYFTSFWTLLDFLIVFVSLFSLLIEENENLKVLR"
            "SLRTLRALRPLRAISRWQGMRIVVNALMYAIPSIFNVLLVCLVFWLIFSIMGVQFFSGKFYKCVDDEGER"
            "LDISVVENKWECENQNYTWMNSKISFDHVGVAYLALFQVATFEGWMEVMADAVDARGVDLQPQREANLYA"
            "YIYFVIFIVCGSFFTLNLFIGVIIDNFNMLKKKYEGGVLEMFLTESQKHYYTAMKKLGRKKPQKVIKRPM"
            "NQFLAMFYDLSNSRRFEIAIFVLIFLNMLSMGIEHYGQPHSVFFVLEVSNAFFTTVFSLEAIVKIIGLRY"
            "HYFTVPWNVFDFLLVLASILGILMEDIMIDFPVSPTLLRVVRVFRIGRILRLIKAAKGIRKLLFALIVSL"
            "PALFNIGALLALITFIYAIIGMFLFGHVRQQGALDDMVNFQTFGRSMHLLFRLITSAGWNDVLESLMIEY"
            "PDCDPHYRNQSNGDCGYPLLAIIYFTSFIIINYMIVINMYIAIILENFNQAHQEEEIGIVEDDLEMFYIR"
            "WSKYDPHATQFIRFTQLSDFIASLDPPLGISKPNTVALVSFNLPIARGNKIHCLDILHALVKHVLGHVEE"
            "TDNFRQLQEQMSIKFKKQFPTRKELEIVSSTRIWKRQDKAARLIQKAYKDYLKRKKEREREAEEIDETTQ"
            "TSSPGGGWQGRLSAFLHVHRGSRASSRKSSRASDASDLSELGGPWLNLPLLLLSSATNMSPEELDLTRDA"
            "ADVSIKVSEASPEAATTPVTPTPQSQPRRRSIYNFPFFLRQDAVENPDEKSSPLLGRKDAKTPSTPQSLH"
            "PGTSDDAKPKRGSIIRRKRVGSVKARPTSVAPSGGCHRSQSEKCSSTDVSILVTEPSPENNLTRPPLNRQ"
            "NSEATVVQVLVHRESEEYNNEEEEELRVPPAAESVSAPSDVSTDVVIDLNGRESTS"
        ),
    },

    "brown_planthopper": {
        "name": "Brown Planthopper",
        "protein": "Chitin synthase CHS-2 isoform X2",
        "sequence": (
            "MTGLRPHLLTNNPGSDDNFSDDEGSPLNQEIYGGSTRTVSETKGWDVFRDLPPKQDSGSMESQVCLEFTV"
            "KILKVIAYLVTFVIVLCSGVLAKGTIFFMTSQLRPDRVLPYCNKDLGRDKQFVVNLPPEERVAWTWCLVV"
            "AFMIPELGTLIRSIRICFFKSWRRPPFNDFMFVFIMESLHVVGLALLVFIVLPNLDVIKGAMLTNCVCFV"
            "PALFSLVSRNTKGCTSRSEKTEVYMKAMVDVVALCAQATGFVVWPALEGSLRPDLWVIPVSLFCISCGWW"
            "ENYVSKHSVFIFMKPLWRVKDRLKRTRYFTYLFISIWKIILFFSCTLAAVFYRGESISKFFTSMSTGFSE"
            "HKIRITEVRASYGGTSLPDLADVIPTGEIIDINAEQKTALMVLTVHIIAAYLCYIFGKFACKIVIQGFSY"
            "AFPVNLTIPVTISVLIAMCGLRQEDPCFFHGTIPDYLFFESPPIYFLNDFISRQHAWIWLVWLLSQTWIT"
            "LHIWTPKVERLATTEKLFVLPMYDALLIDQSLGLNRRRDDDKDVKTEELAEREKDPDEYYETISVHTDAS"
            "STTPKTVKKSDSITRIYACATMWHETKEEMMEMLKSILRMDEDQCARRVAQKYLRVVDPDYYEFETHIFM"
            "DDAFEISDVNDDWCQVNRFVKLLISIIDEAASHVHETNIRIRPPTKYPTVYGGRLVWTLPGKTKMICHLK"
            "DKAKIRHRKRWSQVMYMYYLLGHRLMELPISVERKEVMAESTYLLTLDGDIDFQPHAVRLLIDLMKKNKN"
            "LGAACGRIHPVGSGPMVWYQMFEYAIGHWLQKATEHMIGCVLCSPGCFSLFRGKALMDDNVMRRYTTRSD"
            "EARHYVQYDQGEDRWLCTLLLQRGYRVEYSAASDAYTHCPESFNEFFNQRRRWVPSTMANIMDLLADYRH"
            "TVKINDNISLPYIWYQIMLMGGTILGPGTIFLMLVGAFVAAFRIDNWTSFYYNIIPIFFFMLVCFTCKAE"
            "IQLFVAQMFSTAYALIMMAVIVGTALQLGEDGWGSPSAIFLTAMLGSFFIAAVLHPQEFKCILPFAIYML"
            "SIPSMYLLLILYSIINLNVVSWGTREVAVKKTKKELEEEKKAEEDAKRKAKARSLLGFLQNEDIGLGNND"
            "DEGSLELSFAGLFRCMFCTYPSPVDEKQQLMRIAETLEAMERRLDTMEKVMDPNSQVIGRRRTTSSSSRG"
            "DHHGGGGGGGGALHALTEDPAEEDQVDDNSDTVSTLATEHRIERNDEFNPYWIEDRDLKKGPVNFLSAAE"
            "NQFWKELLDKYLFPIDEDKAEKARIAADLIELRNKAVFAFFMINALFVLIVFLLQLNKDSIHVEWPFGVR"
            "TNITYVEETAEVLISKEYLQLEPIGLVFVFFFALILVIQFTAMLFHRFGTISHILASTELNWCFSKKVED"
            "MSQDKLLDKQAVDIVRHLQRLKGINGDYDNDSGSSGDRVGRRRTIYNLEKQRHKTRTIGTLDVAFRKRFL"
            "QMKMEDGEEAAGTPVLGRKLTMRREVREALEVRRRSLQAERRKSQMQTLGAAHARNPRVSNAGMSVKDLF"
            "EGHPNPAYEHGEDDTSSLRLQSVARNWAELERTSNSHM"
        ),
    },

    "mosquito_larvae": {
        "name": "Mosquito Larvae",
        "protein": "Acetylcholinesterase",
        "sequence": (
            "MKMSAVVRLCCNMISLLLCITVISPVYGIFDRLVVQTSSGPIRGRSTMVLGREVHVFNGVPFAKPPVDGL"
            "RFRKPVPAEPWHGVLDATRLPPSCIQERYEYFPGFAGEEMWNPNTNVSEDCLYLNIWVPTKTRLRHGRGL"
            "NFGNNDYFQDDDDFQRQHQSKGGLAMLVWIYGGGFMSGTSTLDVYNAEMLAAVGNVIVASMQYRVGSFGF"
            "FYLAPYLNDDDAPGNVGLWDQALAIRWLKENAKAFGGDPDLITLFGESAGGSSVSLHLLSPVTRGLSRRG"
            "ILQSGTLNAPWSHMSAEKALSVAEALIDDCNCNVTLLKDNPNYVMNCMRNVDAKTISVQQWNSYSGILGF"
            "PSAPTIDGVFMTADPMTMLREANLEGVEILVGSNRDEGTYFLLYDFIDYFEKDAATSLPRDKFLEIMNTI"
            "FSKASEPEREAIIFQYTGWESGNDGYQNQQQVGRSVGDHFFICPTNEFALGLAERGASVYYYYFTHRTST"
            "SLWGEWMGVLHGDEVEYIFGQPMNVSMQYRQRERDLSRRMVLSVSEFARSGNPALEGEHWPVYTKENPIY"
            "FIFNAEGEDDLRGEKYGRGPMATACAFWNDFLPRLRAWSVPPKSSCNILEQTSAATILYVDIKIVTVLMV"
            "FILVRLY"
        ),
    },
}